Public Class Form1

    Private Sub btnCalculate_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnCalculate.Click
        ' Constants
        Const dblCOST_A As Double = 15.0   ' Class A seat ticket price. ($15.00)
        Const dblCOST_B As Double = 12.0   ' Class B seat ticket price. ($12.00)
        Const dblCOST_C As Double = 9.0    ' Class C seat ticket price. ($ 9.00)

        ' Variables
        Dim intSoldA As Integer     ' The number of Class A seat tickets sold.
        Dim intSoldB As Integer     ' The number of Class B seat tickets sold.
        Dim intSoldC As Integer     ' The number of Class C seat tickets sold.

        Dim dblRevenueA As Double   ' The revenue generated by Class A seat ticket sales.
        Dim dblRevenueB As Double   ' The revenue generated by Class B seat ticket sales.
        Dim dblRevenueC As Double   ' The revenue generated by Class C seat ticket sales.

		Dim dblTotal As Double		' The total revenue generated by all ticket sales.
		lblStatus.Text = String.Empty

		Try
			' Get the number of seat tickets sold for each class as input from the user.
			intSoldA = CInt(txtSoldA.Text)
			intSoldB = CInt(txtSoldB.Text)
			intSoldC = CInt(txtSoldC.Text)

			' Calculate the revenue generated for each class of seat tickets sold.
			dblRevenueA = dblCOST_A * intSoldA
			dblRevenueB = dblCOST_B * intSoldB
			dblRevenueC = dblCOST_C * intSoldC

			' Calculate the total revenue generated by all seat ticket sales.
			dblTotal = dblRevenueA + dblRevenueB + dblRevenueC

			' Display the results.
			lblRevenueA.Text = dblRevenueA.ToString("c")
			lblRevenueB.Text = dblRevenueB.ToString("c")
			lblRevenueC.Text = dblRevenueC.ToString("c")
			lblTotal.Text = dblTotal.ToString("c")
		Catch
			lblStatus.Text = "Please enter integer values"
		End Try

	End Sub

    Private Sub btnClear_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnClear.Click
        ' Clear the text boxes.
        txtSoldA.Clear()
        txtSoldB.Clear()
        txtSoldC.Clear()

        ' Clear the labels.
        lblRevenueA.Text = String.Empty
        lblRevenueB.Text = String.Empty
        lblRevenueC.Text = String.Empty
        lblTotal.Text = String.Empty
		lblStatus.Text = String.Empty

        ' Reset the focus.
        txtSoldA.Focus()
    End Sub

    Private Sub btnExit_Click(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles btnExit.Click
        ' Close the form.
        Me.Close()
    End Sub
End Class
